version: "3.3"
services:
  crawler:
    image: crawler:latest
    build: crawler/
    restart: always
    ports:
      - "3000:3000"
  rest-api:
    image: rest-api:latest
    build: rest-api/
    restart: always
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "5000:5000"
  scheduler:
    image: scheduler:latest
    build: scheduler/
    restart: always
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: preiswecker
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  reverse-proxy:
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./reverse-proxy/ssl.crt:/etc/ssl.crt:ro
      - ./reverse-proxy/ssl.key:/etc/ssl.key:ro
  frontend:
    image: frontend:latest
    build: frontend/
    restart: always
    environment:
      VUE_APP_API_URL: "https://preiswecker.spyfly.xyz/api"
    ports:
      - "80:8080"