version: "3.3"
services:
  crawler:
    image: crawler:latest
    build: crawler/
    ports:
      - "3000:3000"
  rest-api:
    image: rest-api:latest
    build: rest-api/
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: preiswecker
