version: "3.3"
services:
  crawler:
    image: crawler:latest
    build: crawler/
    restart: always
    ports:
      - "3000:3000"
  rest-api:
    image: rest-api:latest
    build: rest-api/
    restart: always
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: preiswecker
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
